apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dpjb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dpjb
    app.kubernetes.io/part-of: tkrw-pr712-0075-0013-app
  name: devfile-sample-dpjb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-dpjb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-dpjb
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-dpjb@sha256:306aa2f1d67d6d0a30a1090c3db2237ea97426793e43af4be4e5ec491723c05d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
